### PR TITLE
[vnc] add option to allow all connections

### PR DESCRIPTION
**Pull request by teleshoes**
author is kimmoli, not me. please merge this @mkosola

### CODE REVIEW

**Comment by Tomin1** [comment]
Given how insecure this VNC implementation is and VNC overall is, we shouldn't expose it on all interfaces. USB is somewhat better because it must be physically connected and you can control whether IP connection is made.

I suggest that you use for example SSH tunnel like mentioned in [libvncserver README](https://github.com/kanaka/libvncserver/blob/0de0fa498d58526bf3516dc23ddf9060baa47808/README#L311).

**Comment by teleshoes** [comment]
i actually am using lipstick2vnc over an ssh tunnel already, and it doesnt work without `--allow-all`. i thought this was deliberate, that it literally had to be USB. ill see if i can figure out why that snippet of network code does not allow connections over ssh tunnel.

**Comment by teleshoes** [comment]
it does require that the device is over usb. if there is somewhere that you check to see if its localhost, i cant find it.

i propose that we add:
`if(remoteAddr.isLoopback()){ allowConnection = true; }`

this doesnt even need a cmdline option, imo. what do you think? @Tomin1

**Comment by teleshoes** [comment]
see #17

**Comment by Tomin1** [comment]
> it does require that the device is over usb. if there is somewhere that you check to see if its localhost, i cant find it.

There probably isn't as the only use case we've had for this was USB.

> i propose that we add: `if(remoteAddr.isLoopback()){ allowConnection = true; }`
> 
> this doesnt even need a cmdline option, imo. what do you think? @Tomin1

Sounds good to me.

**Comment by teleshoes** [comment]
superseded by #17

**Pull request closed without merging**
